### ISSUE TITLE
Add song count to Categories and Languages in search.

### ISSUE THREAD

**Issue by dinshaw** [dinshaw/CircleSongs#25]
It's hard to know why a given search returns 0 songs. It might be nice if there was a count next to each search option like
- [ ] Popular (5)
- [ ] Traditional (3)
- [ ] Sacred (1)

**Comment by dinshaw** [comment]
@Zanspins what do you think?

**Comment by Zanspins** [comment]
I think it's a great idea. Let's do it. 
I still need to re-think the categories. I'll take a crack at it now.
