### ISSUE TITLE
Privacy Shield

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#29]
I have 40 tracks I can put up, beautifully recorded by Munay choir, once we figure out the secret side of the website. 
What about a subdomain like icaro.medicinesongs.net 
It could have an identical architecture installed, but a separate database of just these song. Access by directly typing in the domain only, and then being prompted for a password to display the content.
I'm open to variations with similar functionality, too.

**Comment by dinshaw** [comment]
# How to indicate a protected song in the admin area
I like the idea of having a separate checkbox call "Protected" or "Private" or something. I don't want to use the categories as i feel like that would be overloading the category responsibility. 

# How to authorize Users 
In order of secure to insecure:
* Individual logins 
  For anyone you want to have access, you would register an account using their email address. Then they would login with a user-specific password and the protected songs would appear in their search results.
* Global Password
  One password that you give to anyone you want. Drawback is that this could easily be shared.
* Security by Obscurity 
  A secret page. Could be something intuitive like `/protected-songs`, or something cryptic like `/xby42$5`. Drawback is that this could easily be shared.
# How to deliver protected songs only to authorized users
* If the user is authorized, automatically include Protected songs in the search results.
* Require authorized users to navigate to a separate page where the protected songs are displayed.

**Comment by dinshaw** [comment]
Totally open to any ideas you have, so let me know if you've envisioned something different, or if you have any examples of other sites that do a good job.

**Comment by Zanspins** [comment]
Thanks for taking a look at this. My thoughts:
I hadn't been thinking of individual logins because

    It takes more time to manage, receive feedback, fix accounts, purge dummy accounts, etc
    It creates a security vulnerability for being hacked. At least I've had several wordpress sites destroyed this way (as well as accumulate thousands of fake users)
    Our community is constantly expanding. Difficult for one person to know everyone. And we'd need to be approving accounts and not giving access to anyone who clicks "register", so there's more tedious admin involved.

If you're picturing something else let me know.

So I was thinking global password. I liked that more than a cryptic link because then it takes 2 things to be shared: link and password. I can't just email all my friends a link and get them in with 1 click. Yes, I realize it's not really more secure, but it is 1 extra layer of inhibition.
If web stats show an over-access issue, we could periodically change the global password, and if people ask us what the new one is we could tell them.

I agree about not making "protected" a category. Would be weird. But that leads me to consider a separate page. Why? Because if you go to the special link and insert the special password and this were to give access to all songs on 1 page (both protected and not), then if you wanted to see the icaros, it seems like they'd need a category. Otherwise they'd be hard to find since 40 songs might be embedded inside hundreds of unprotected ones...
Do you see what I mean? How do you find icaros if they're all on one page and there's no category?

Your thoughts on any/all of this?

**Comment by dinshaw** [comment]
OK, so I'm back to using the categorization then. How about this:
* We add "Icaros" as a "Protected Category" (I will provide some interface for this in the admin area).
* You categorize all the Icaros as such.
* By default, "Icaros" (protected categories) do not appear in the category selector.
* By default, songs categorized as Icaros do not appear in the search results.
* If the user has entered the username:password, only then will the category "Icaros" appear in the categorization filters.  
* Once you select icarus, then you see only Icaros as per #34

**Comment by dinshaw** [comment]
Would you like a visible login link or a secret page?
The visible link could be fairly subtle, like in the fine-print of the footer.
The secret page could be easy to remember `/sacred-songs` or cryptic `/xxkbj7462#$`

**Comment by Zanspins** [comment]
I have one additional thought (I'll mention that first) that leads me to a revised model that incorporates what you've said (described after).

It may be that individual songwriters prefer to have their songs not publicly visible in conjunction with this site. For example, the Munay songbook has songs written by Lisa, Glen, Me, Britta, Ishmiel, etc. Let's say Lisa or Glen, for personal/professional reasons, want only Munay folks to see their songs. But those songs aren't icaros.

So how about this:

- Make a category for icaros, hidden by default. You already described this.
- Make a category for "protected", also hidden by default. It will pretty much always be used in conjunction with another category. For an icaro, I'd mark "icaro" and "protected". For Glen's "Munay" I could mark "popular" and "protected", if that is his wish. 

Then, when someone opens the protected space:

- They can select "icaros" and see all of them
- They can select "protected" and see all icaros plus other protected songs together.
- They can select "popular" and see Glen's song mixed in with the unprotected popular songs

As for how to access it, how about a combination:

1. A direct, memorable link like 
sacred.medicinesongs.net
OR
medicinesongs.net/sacred

2. An innocuous hidden link in the footer. Example text "Gratitude". 

For both of these, the site will prompt for the entry of a password. No users or login.

What do you think?

**Comment by dinshaw** [comment]
I like it.
