### ISSUE TITLE
Image on song page

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#33]
On the phone we discussed including an input for an image for each song. It would display once at the top (small, to the left of the song title and secondary title) and once again at the bottom, larger. 

I just tried to figure out AWS S3 to upload a test image, but it looks like there are enough setting that I've never heard of that perhaps you should be the out to hammer out the initial configuration, then I can put some images in. 
Please suggest an aspect ratio.

**Comment by dinshaw** [comment]
You will not use AWS to upload the images. With any luck, you'l never have to login to it again.
I will pull an API token from your account and then add the image upload field to the admin area for songs.
