### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by dinshaw** [dinshaw/CircleSongs#36]
@Zanspins you have mentioned tracking traffic a couple of times. If you'd like to do that, the easiest way is probably a Google Analytics account. The other ways would be for you to login to Heroku and learn to read the output of the analytics tools that they offer.
Either way, although I will be curious at first, I can't really commit to always monitoring this for you, so you will need to learn one tool or the other if you think that knowing the traffic will be important to you.
If you do want to do GA, we will use this ticket to log the work.

**Comment by Zanspins** [comment]
Let's go with google analytics for ease. I would not expect you to monitor the traffic, or wish that upon you. I just want to be able to reference it if i'm curious or it becomes useful. 
Will it be able to track how many people log in to the secret songs, too?
Seems like we have to wait until we're live on medicinesongs.net before installing the analytics, right?

**Comment by dinshaw** [comment]
Cool. Yes, it won't start until the site is live because it works off the domain.
You can go ahead and set up your GA account. I think you can then invite me as a collaborator or something. It's pretty complicated as i recall. Use my regular email address.
I would imagine it can tell you how many logins. We can track that pretty easily, too, if it doesn't.

**Comment by Zanspins** [comment]
You are added as a user. Also, their info on site tagging is below:

Global Site Tag (gtag.js)
This is the Global Site Tag (gtag.js) tracking code for this property. Copy and paste this code as the first item into the <HEAD> of every webpage you want to track. If you already have a Global Site Tag on your page, simply add the config line from the snippet below to your existing Global Site Tag.


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-134757294-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-134757294-1');
</script>
