### ISSUE TITLE
Footer / space at bottom

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#37]
I've put up a few songs today. Look at "Shine".
Right now, immediately below the chords the page ends. There should at least be a little blank space. But I know you already mentioned a footer, so I assume that will cover it.

**Comment by dinshaw** [comment]
Correct. Usually people put links to things like `contact us`, copyright info, and stuff which may not be applicable to you. Anything you would like there? If not, we will just add an aesthetically pleasing spacer.

**Comment by Zanspins** [comment]
The footer could have a link for contacting us with issues, broken links, and suggested versions of songs. I'll make a new issue for a contact page.
The footer needs to have a secret link for login. Maybe it could be within text, like: "This page is created with deep respect and gratitude for all those who have developed, cultivated, and passed on the knowledge and traditions of healing with sound, music, and vibration. Great thanks to the composers of these songs, to all that inspired them, and to all of our teachers on this path. May we each cultivate our authentic gifts in service to a greater harmony." Then a word or phrase could be the login link, like "traditions of healing".
