### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#38]
I'd like people to be able to notify us of broken links or other issues. Plus, be able to suggest a new version or a new song. 
I'd like the receiving email to be anonymous, or at least not directly linked to me.
I have medicinerising@gmail.com
Or we could make one like contact@medicinesongs.net

**Comment by dinshaw** [comment]
@Zanspins A contact form is, imo, a little old-school and also creates problems with spam. I'd recommend just setting up the email and having a some "quick links" in helpful places, like "Report broken link" next to recordings that are not working. The link would create an email for the user and pre-populate the subject and body with the info. 

On the other hand, if you think people would like to be able to report stuff and stay anonymous, then the form would be the way to go.

**Comment by Zanspins** [comment]
That seems like a fine solution to me. I will be away from home until
April 1. I won't be able to do much work until then. I can set up the email
at that point. Do you suggest a Gmail or the email from this domain? And
when  is the appropriate point to migrate to the domain I have?

**Comment by dinshaw** [comment]
medicinesons@gmail.com  will be easer and cheeper. If you are cool with not using the custom domain, I'd go with that.

**Comment by dinshaw** [comment]
Also, to manage the DNS for you domain, I've created #46
