### ISSUE TITLE
CloudFlare account

### ISSUE THREAD

**Issue by dinshaw** [dinshaw/CircleSongs#46]
I need one more, free account set up to manage the DNS of your domain, please.
https://www.cloudflare.com

**Comment by Zanspins** [comment]
Account Created:
zan@munayislove.com
8Vh2$@XB!Y^Y

**Comment by Zanspins** [comment]
I just confirmed the email address for them. Anything else for me to do there?

**Comment by Zanspins** [comment]
I linked the DNS records to cloud flare. Also created the info@ account that's managed through google.
