### ISSUE TITLE
Search dropdown: "All"

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#53]
I searched for a particular category. Then, I wanted to go back to looking at all songs. But the category dropdown has no option to re-select "All". All I could do was choose a different category. Can we add "All" as a selectable option?

**Comment by Zanspins** [comment]
I guess the "Clear" button in the search bar takes care of this. But I didn't notice it the first time when looking to select "All" again from the drop down. So this still might be a good option for a functional addition.

**Comment by dinshaw** [comment]
Makes sense...
