### ISSUE TITLE
Underlining song text

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#55]
In our printed songbook, we underline the parts of a song verse that get substituted out for a new word each time. Is there any way to incorporate that into the 'lyrics' and 'translation' text fields? Such as a basic [u] underline [/u] tag?

**Comment by dinshaw** [comment]
This is done. However the HTML tag looks like: <u>Underlined text</u> (not [u]...[/u])

**Comment by Zanspins** [comment]
Dinshaw-
I'm not exactly clear how to use this function. Your description of the tag
to use was limited. Can you simply write an example of the code for any
song lyric with a section underlined, and put it in a response email?

**Comment by dinshaw** [comment]
Easies way should be to edit La Aurora and see what I have done. But the tag looks like <u>text you want underlines</I>
