### ISSUE TITLE
Link from song admin to front end

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#56]
I am often looking at a song on the admin side, and want to see what it looks like on the front end. Can you add a link from a song's admin page (not editing or creating, just viewing) that opens a new window of looking at it's page out front? It would save me going to the home screen and searching for it.

**Comment by Zanspins** [comment]
To clarify, if I'm editing "El Condor Pasa" and I want to see what the changes look like, I want an accessible link to the front-end view of "El Condor Pasa" specifically. Seems like a target=blank would be the way to go. In the end, it's similar to the "preview changes" function when editing wordpress sites, but will only reflect saved changes. 
In private email you suggested that I should click "Medicine Songs" up top to reach the front end. But that's what I've been doing, then having to search for the new song.

**Comment by dinshaw** [comment]
There is now a Preview link at the top of the song details on the Song show page.
