### ISSUE TITLE
Admin accounts

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#58]
How are accounts managed?
Seems like we should get rid of admin@example.com and make passwords of normal strength. I might as well use the email I set up for this site:
info@medicinesongs.net

**Comment by dinshaw** [comment]
This is done. You can use the forgot password workflow to update the password for info@medicinesongs.net. Let me know if you have trouble.

**Comment by Zanspins** [comment]
No dice. I tried from 2 browsers. It says there's an error in the reset password application.

**Comment by dinshaw** [comment]
#64 should fix this. Stand by...

**Comment by dinshaw** [comment]
This works now.

**Comment by Zanspins** [comment]
I still can't get the password to reset on any browser. :(

**Comment by dinshaw** [comment]
What happens? The password is still “password”, though...

**Comment by dinshaw** [comment]
NM, I see. One min

**Comment by dinshaw** [comment]
OK, try again, please... Close this, if it works.

**Comment by Zanspins** [comment]
it's working now.
