### ISSUE TITLE
Secret songs' password

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#59]
Should we make a way for admins to change the icaro access password on the back end, or does it make sense for only you to have that power?
On the one hand, I don't want to have to trouble you in the future. On the other hand it might give us more security...
Your thoughts?

**Comment by dinshaw** [comment]
This is done. You can edit it in the admin area under 'Passwords'. There will probably only ever be one, "Restricted Songs". But you never know...
