### ISSUE TITLE
Unable to use # sign for sharp chords

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#93]
Someone putting in data for me (also a guitar player) sent me this comment:
"Sol Qi - When trying to add sharp chords C#m7 G#m7 F# ect.. It appears that in the Chord Input section that the “#” symbol removes everything that follows it on that line. I thought i just copied and pasted some weird code so i manually input each chord and the same thing happened. A few quick fixes would be: Change chords to flat chords or use the word “sharp” instead of the pound sign, this doesn't solve the problem for the future but can work here. Leave the alternate chord voicings only to be found in the book . Or find a way to add sharps in the chord section. Its possible that there is a system in place, like the [ ] that would work but not sure what it is. "

Can you find a way to allow us to use the # sign? Gracias

**Comment by dinshaw** [comment]
I should be able to figure this out. I’ll try look tomorrow at latest.

**Comment by dinshaw** [comment]
So... the "chords" section is parsed by a javascript library that only expects the lyric/chord format:
https://github.com/martijnversluis/ChordSheetJS
It is not expecting "normal" text like the chord description you are putting in (I'm working on some way to add chord forms, but haven't found a good solution yet).
In the meantime you can wrap your chord names in brackets like so: `[C#m7]` and it should render fine. However, it will put any text that follows on a new line.
A couple other ways to handle this:
* Have a separate section in the CMS that takes normal text called "chord forms"
* Have a separate section in the CMS that uses some chord from generating syntax to get cool graphical chord forms - I'm still investigating this.
* Have separate page that has lots of chord form notation in one way or another.

**Comment by Zanspins** [comment]
Of your three options, I don't like number 3. The specific chord forms are usually for 1 song only. I wouldn't want to bounce people around, but rather keep the information localized and self-contained. 
Adding a new section called "chord forms" and having it display below the chords+text section seems like a fine idea.
