### ISSUE TITLE
Donation button

### ISSUE THREAD

**Issue by Zanspins** [dinshaw/CircleSongs#96]
Donation button code below (includes your suggested 'thank you' page url: https://www.medicinesongs.net/donation_thank_you )

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="BGY3UGYELUY5J">
<table>
<tr><td><input type="hidden" name="on0" value="Let your love abound!">Let your love abound!</td></tr><tr><td><select name="os0">
	<option value="Love droplet">Love droplet $5.00 USD</option>
	<option value="Love potion">Love potion $10.00 USD</option>
	<option value="Love tsunami">Love tsunami $25.00 USD</option>
	<option value="Love supernova">Love supernova $50.00 USD</option>
</select> </td></tr>
</table>
<input type="hidden" name="currency_code" value="USD">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynow_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

**Comment by dinshaw** [comment]
What would you like the thank you page to say?

**Comment by Zanspins** [comment]
How about the page is a copy of the main page (song database) with an extra header at the top. The header says:
"Thank you so much for your generosity! You make it possible to keep this site growing and thriving. Thanks for feeding what feeds you. May these songs open your heart and inspire you."
